### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ragmha** [ragmha/eH-reduce-data-array#1]
- [ ]  Use case for reduceRight 🤔 
- [ ] More examples of reduce   🤔 
- [ ] Look into composition  🤔 
- [ ] Try more nested object  🤔
